### ISSUE TITLE
SSL proxy is not set

### ISSUE THREAD

**Issue by scizeron** [callmeal/Flickr4Java#114]
Hello,
In the com.flickr4java.flickr.REST class, the setProxy is incomplete, the following properties "https.proxyHost" and "https.proxyPort" are missing.

- UnknownHostException api.flickr.com without https proxy properties
- if I add the 2 underlying properties, it's OK : 
      System.setProperty("https.proxyHost", proxyHost);
      System.setProperty("https.proxyPort", proxyPort);
Regards
Stéphane

**Comment by boncey** [comment]
Hi, have just fixed this, will release soon.
