### ISSUE TITLE
add sold product sku, sold product order id in sold product report in magento 1.8.1?

### ISSUE THREAD

**Issue by pankaju** [callmeal/Flickr4Java#123]
i want sold product sku's and order id in below
code\core\Mage\Adminhtml\Block\Report\Product\Sold\Grid.php

i tried to below code but showing blank

$this->addColumn('sku', array(
            'header'    =>Mage::helper('reports')->__('SKU'),
            'index'     =>'sku',
        ));
		$this->addColumn('order_increment_id', array(
            'header'    => Mage::helper('reports')->__('Order'),
            'index'     => 'order_increment_id',
        ));

**Comment by boncey** [comment]
Closed as bollocks. :-)
