### ISSUE TITLE
Is it possible to validate an Authentication store?

### ISSUE THREAD

**Issue by Linus12** [callmeal/Flickr4Java#126]
I borrowed some code from the "backup example" especially in the area of authentication. I set up my class to store the Authentication credentials so that the user didn't have to keep Authorizing every time they ran the app.

My Flickr App authenticates the user, then stores the whole thing to an Authentication file. When the app is re-run later, the user can enter the NSID they used before and the app calls the following:
     public boolean auth_Needed() { 	
        RequestContext rc    = RequestContext.getRequestContext();

        if (this.authStore == null) {
        	System.out.println("You must set the Authentication Storage Directory before " + 
                               "authenticating a user.");
        	return false;
        }
     
        Auth auth = this.authStore.retrieve(this.nsid);  // Retrieve store for the set nsid
        if (auth != null) {
            rc.setAuth(auth);
            this.username = auth.getUser().getUsername();
            return true;
        }
    : 
    : 

This is working fine, however I have two concerns.
1. The Authorization file itself could be corrupt between runs, or
2. The user could have "Unauthorized" the app from within Flickr

At this point in the code however, we don't know this. 

Later when a Flickr call is made that requires authentication, an Exception is thrown and the program fails.

Now I could catch that specific exception (I think) any time it is thrown, and then proceed to ask the user to re-authenticate. But that seems a bit extreem to handle this for every Flickr call.

If the validation fails after the restore, I can easily ask them to go through the Authentication process again.

Is there a method within Flickr4Java that would validate the just restored Authentication information? Assume the user has just started using Flickr, has no photos, joined no groups, and is running in "Read only" mode. 

I think it'd be quicker to call something after retrieving the authentication store, to verify it still works, then waiting for something to happen later.

Or am I just being paranoid and if I really want to do this just add a call to something like 

    com.flickr4java.flickr.people.PeopleInterface.getLimits()

and catch the exception, or toss the results if everything is fine?

I will concede that the user could "Unauthorized" the program in Flickr, while it is running, but that is not something that would happen very often.

**Comment by boncey** [comment]
I think a call could be made to `flickr.auth.oauth.checkToken` from within the authentication store.
This seems non-critical and my time for F4J is limited so I won't add it myself but I welcome any patches for this.
