### ISSUE TITLE
How to index binary files in elasticsearch.net? 

### ISSUE THREAD

**Issue by mahsa86** [callmeal/Flickr4Java#131]
Hi, 
I am a beginner in Elasticsearch. I have installed elasticsearch and using Marvel plugin for managing the elasticsearch. I need to index a list of binary documents such as word, pdf, excel,...
Does anyone can help me by a sample code for how to post the document to Elasticsearch?

**Comment by mahsa86** [comment]
Hi,
Sorry! Can I ask why you have closed my question?
If here is not the right place ti ask questions, please let me know where to ask? I really need some help regarding Elasticsearch.net subject.

Thanks.

**Comment by boncey** [comment]
I closed it because it has nothing to do with Flickr4Java.
I'm curious what made you think it might be though - for some reason this project gets lots of irrelevant questions.

**Comment by mahsa86** [comment]
So, Would you please let me know where is the right place to ask questions regarding Elasticsearch.Net issue?

**Comment by boncey** [comment]
Sorry, I don't know.
