### ISSUE TITLE
Mongo Queries on IMongoCollection for Searching Arrays

### ISSUE THREAD

**Issue by arvindcharyn** [callmeal/Flickr4Java#136]
I have started working with Mongo Database. I am writing my Mongo queries in c#.net. Can you please help me in writing the Mongo Database queries in c#.net. Thanks in advance for your help and support. I am using Mongo CSharpDriver-2.0.0 version and IMongoCollection Async in my application. My data collection looks as shown in the figure:
![issue](https://cloud.githubusercontent.com/assets/12831464/8086361/a630c4d4-0fb2-11e5-977e-045ddfe66413.png)

Here I want to perform a Search operation on Categories, basically we will give comma separated list of Category Names and it should return a list of Records that are matching the categories that are provided as input. 
To implement above functionality I am using the below code: This code works fine when I pass a single category. 

var collection = _database.GetCollection<BusinessDeal>("BusinessDeals");
var filter = Builders<BusinessDeal>.Filter.Eq("Categories.CategoryName", categorylist) | Builders<BusinessDeal>.Filter.Eq("Accessgroups.AccessgroupName", groups);
var result = await collection.Find(filter).ToListAsync();

But my requirement is to get the records when I provide a Comma separated categories List. For that implementation I have implemented the following code:
                var collection = _database.GetCollection<BusinessDeal>("BusinessDeals");
                var filter = Builders<BusinessDeal>.Filter.AnyIn("Categories.CategoryName", categorylist.Split(',').ToArr()) | 
                              Builders<BusinessDeal>.Filter.AnyIn("Accessgroups.AccessgroupName", groups.Split(',').ToArr());
                var result = await collection.Find(filter).ToListAsync();
The above code is not returning any results and throwing error as “Not Yielded any Results” and Status message as “Failed”.

My another requirement is get nearest location records, for this implementation is implemented the following code:
  
                var keyBuilder = Builders<BusinessDeal>.IndexKeys;
                //var keys = keyBuilder.Geo2DSphere("ven.loc").Ascending("cat._id");
                keyBuilder.Geo2DSphere(x => x.Venuedetails.Select(y => y.Location)).Ascending(x => x.Categories.Select(y => y.Id)); 
                keyBuilder.Geo2DSphere(x => x.Venuedetails.Select(y => y.Location)).Ascending(x => x.Accessgroups.Select(y => y.Id));

                BsonDocument geoPoint = new BsonDocument
                {
                    {"type","Point"},
                    {"coordinates",new BsonArray(new Double[]{Latitude, Longitude})}
                };

                BsonDocument geoNearOptions = new BsonDocument
                {
                    {"spherical", true},
                    {"limit", 0}, //need to test to see what limit is appropriate, should we do a filter first?
                    {"maxDistance", 0},
                    //{"query", queryDoc}, //may need to implement for speed
                    {"near",geoPoint},
                    {"distanceField","dist"}
                };

                var stage = new BsonDocumentPipelineStageDefinition<BusinessDeal, BusinessDeal>(new BsonDocument { { "$geoNear", geoNearOptions } });
                var colAggregate = collection.Aggregate().AppendStage(stage);

This above is also not working.

Can you please help me to proceed further. Thanks in advance for your help and support.

**Comment by farnulfo** [comment]
Do you understand that you post an issue about a MongoDB thing on a java project about Flickr image hosting. No related at all.

For my understanding, how do you come here ?

**Comment by arvindcharyn** [comment]
can you please help me how can I reach there?

**Comment by farnulfo** [comment]
Ask your question on http://stackoverflow.com
