### ISSUE TITLE
REST.<clinit> NoClassDefFoundError

### ISSUE THREAD

**Issue by AlexandroKurchenko** [callmeal/Flickr4Java#137]
I am trying to authorization wth Flickr4java on android 5.0.1 and on android 4.2.2 (on this devise app crash always ) ,and having some Error with REST

<pre> 
06-15 13:55:29.301   9888-10106/com.my.app W/System.err﹕ log4j:WARN Error during default initialization
06-15 13:55:29.301   9888-10106/com.my.app W/System.err﹕ java.lang.NoClassDefFoundError: Failed resolution of: Ljava/beans/Introspector;
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:140)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:805)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at org.apache.log4j.Logger.getLogger(Logger.java:117)
06-15 13:55:29.306   9888-10106/com.my.app W/System.err﹕ at com.flickr4java.flickr.REST.<clinit>(REST.java:46)
</pre>

Code where it happens:
<pre>
Properties properties;
                InputStream in = null;
                try {
                    in = getActivity().getAssets().open("setup.properties");
                    properties = new Properties();
                    properties.load(in);
                } finally {
                    IOUtilities.close(in);
                }
                Flickr.debugRequest = false;
                Flickr.debugStream = false;
                String key = properties.getProperty("apiKey");
                String secret = properties.getProperty("secret");
                flickr = new Flickr(key, secret, new REST());
</pre>

I am using : flickr4java-2.12.jar , scribe-1.3.7.jar, log4j-1.2.17.jar like say Redme on pain page, perhaps i am using wrong library? Sorry about this question if i post this not there where it is necessary.
Thanks.

**Comment by farnulfo** [comment]
Flickr4Java use log4j library which use by default the java.beans.Introspector class that don't exist on Android platform.
Full explanation on :  http://mindpipe.blogspot.fr/2011/11/android-log4j-exception-properties.html

There is a library (https://code.google.com/p/android-logging-log4j/) that you can use to avoid log4j to call the missing class.

Check the use case "Using log4j directly" : 
https://code.google.com/p/android-logging-log4j/#Using_log4j_directly

**Comment by AlexandroKurchenko** [comment]
Thanks for quick answer.
Have flickr4java calback ? i have outhoriza with webview and see code wich i must past to code, support some calback that return me a code?
Now i am using this for getting url: <pre>authInterface.getAuthorizationUrl(token, Permission.WRITE);</pre>
Thanks.

**Comment by farnulfo** [comment]
Did the android-logging-log4j resolve your initial issue ?
So @callmeal can close this.

For your other question, please create another issue with more details.

**Comment by AlexandroKurchenko** [comment]
No if i  use android-log4j.jar , the programm crash with <pre>java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/log4j/Logger;</pre> on this code new REST()

**Comment by LuizGadao** [comment]
I'm with the same problem.

**Comment by boncey** [comment]
This looks to be Android specific which I have no experience.
I'll close for now but I welcome any thoughts on how to make F4J compatible with Android without substantial refactoring.

Also, I can add something to the README if someone can suggest some steps to follow.
