### ISSUE TITLE
Change needed to photos.Sizes class due to changesin Flickr data (see second response)

### ISSUE THREAD

**Issue by Linus12** [callmeal/Flickr4Java#141]
Received the following when getting photosizes:

    Exception in thread "Thread-5" java.lang.NumberFormatException: For input string: ""
    	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    	at java.lang.Integer.parseInt(Integer.java:592)
    	at java.lang.Integer.parseInt(Integer.java:615)
    	at com.flickr4java.flickr.photos.Size.setWidth(Size.java:264)
    	at com.flickr4java.flickr.photos.PhotosInterface.getSizes(PhotosInterface.java:755)'

I used the Flickr API screens to see what the issue was and found what I think is the problem:
    .
    .    [some records removed to see the problem better]
    .
    -size label="Original" width="1920" height="1080" source="https://farm4.staticflickr.com/37....jpg" url="https://www.flickr.com/photos/e.../o/" media="photo" />
    -size label="Video Player" width="" height="" source="https://www.flickr.com/apps/video/stewart.swf?v=15...446" url="https://www.flickr.com/photos/...89/" media="video" />
    -size label="Site MP4" width="" height="" source="https://www.flickr.com/photos/e...46/" url="https://www.flickr.com/photos/e...89/" media="video" />
    -size label="Mobile MP4" width="480" height="360" source="https://www.flickr.com/photos/e...46/" url="https://www.flickr.com/photos/e...89/" media="video" />
    -size label="HD MP4" width="0" height="720" source="https://www.flickr.com/photos/e...46/" url="https://www.flickr.com/photos/e...89/" media="video" />

Two of the videos have null widths and heights, and one has a width of 0 but a height of 720. While this may or may not be a loading issue with Flickr, I am seeing it more and more on videos that were uploaded from people's phones.  In all cases, the videos where the sizes are null are viewable and downloadable (where allowed), but these values cause the Flickr4Java to throw the above Exception.

Since the routine is in a tight loop, even handling it back in the calling program doesn't help because there is no way to know if there are additional sizes available.

**Comment by Linus12** [comment]
More research: The fix can be done with two lines of code in the <b>com.Flickr4java.flickr.photos.Size</b> class, procedures <i>setWidth(String width)</i> and <i>setHeight(String height)</i>. 

The issue isn't null values, which are checked for but rather EMPTY STRINGS being returned by the Flickr API.

Depending on maintaining backwards compatibility with pre-1.6 java, the fix would be as follows:

   ```java
        public void setWidth(String width) {
    
          //if (width != null) {
          //if (!width.isEmpty()) {
          // or
          // if (!("".equals(width))) {   // maintains pre 1.6 java compatibility
          // or
          if (!(width == null || "".equals(width))) {   // checking both  

                setWidth(Integer.parseInt(width));
            }
        }
 ````
Likewise for setHeight:
   ```java
    public void setHeight(String height) {

        //if (height != null) {
          //if (!height.isEmpty()) {
          // or
          // if (!("".equals(height))) {   // maintains pre 1.6 java compatibility
          // or
          if (!(height == null || "".equals(height))) {   // checking both  

            setHeight(Integer.parseInt(height));
        }
    }
````

As I have never updated and sumbitted fixes for GitHub before, I'd be more than happy to make the changes and submit them, if someone would point me in the right direction.

**Comment by boncey** [comment]
I've pulled in your change request now so will close this.
Thanks again for your fix.
