### ISSUE TITLE
getImageAsStream of PhotosInterface.class (com.Flickr4java.flickr.photos) should use HTTPS

### ISSUE THREAD

**Issue by Linus12** [callmeal/Flickr4Java#146]
The current (v2.12) code for getImageAsStream of PhotosInterface.class (com.Flickr4java.flickr.photos) uses the HTTP protocol when it should use the HTTPS protocol:

        HttpURLConnection conn = (HttpURLConnection) url.openConnection();

It should use 

    HttpsURLConnection conn = (HttpsURLConnection) url.openConnection();

And the associated include:

    import java.net.HttpURLConnection;

should change to:

    import java.net.HttpsURLConnection;

**Comment by boncey** [comment]
I've made this change and will release soon.
There is no test coverage around this so I'd appreciate a thumbs up from you if it does the trick.
