### ISSUE TITLE
waitTransitionEnd() timeout in  md-menu 

### ISSUE THREAD

**Issue by sachila** [callmeal/Flickr4Java#151]
hi guys, 
i'm using latest version of material design (0.10.1) and i'm currently  working on md-menu items, so when i click a button it appear set of menu item options and i can select a item. so far it's working perfectly. but some time when i select items several times whole screen freeze and i need to refresh the page. it gives this error

"InterimElement.show() error: waitTransitionEnd() timeout"

i was wondering if it's a framework bug because several guys i know got the same problem. 
remember it does't give this error very often. 
Thanks in advance

**Comment by boncey** [comment]
This doesn't appear to have anything to do with Flickr4Java.
