### ISSUE TITLE
getAllSizes on photo object

### ISSUE THREAD

**Issue by cberigan** [callmeal/Flickr4Java#155]
This would help to reduce complexity when trying to get all available sizes from a photo as an alternate to making an extra API call through flickr.photos.getsizes.

**Comment by boncey** [comment]
Can you give a bit more information on how you would expect this to work please?
I'm struggling to know what you actually want the code to do.

Thanks, Darren.

**Comment by cberigan** [comment]
I'm on my phone so excuse me if I don't remember correctly, but I do
remember having to make an extra api call to get the sizes in a collection.
It was difficult to get it directly from the photo object because there
were only getters for each individual photo size.

**Comment by redwerk** [comment]
Hi @boncey , i could do the pull request if no one develops this issue.

**Comment by boncey** [comment]
Hello.
Yes, that's a good idea, then you'll get something that does exactly what you want. :-)
Thanks.

**Comment by boncey** [comment]
Hello, this is merged in and I've done a release.

Thanks again for doing this.
