### ISSUE TITLE
100: Invalid API Key in reorderPhotos

### ISSUE THREAD

**Issue by miguelD73** [callmeal/Flickr4Java#157]
Exception in thread "main" com.flickr4java.flickr.FlickrException: 100: Invalid API Key (Key has invalid format)
	at com.flickr4java.flickr.photosets.PhotosetsInterface.reorderPhotos(PhotosetsInterface.java:642)

WIth the following code:

final PhotosetsInterface photosetsInterface = flickrUtil.getFlickr().getPhotosetsInterface();
(
flickrUtil.getFlickr() -->
        final REST rest = new REST();
        //      rest.setHost(svr);
        return new Flickr(getApiKey(), getSharedSecret(), rest);
)

photosetsInterface.getPhotos("72157650644794663", 500, 1); --> Works well

photosetsInterface.reorderPhotos("72157650644794663", "17829357862,19918596240,17761881671"); --> give the 100:invalid API Key

**Comment by miguelD73** [comment]
Sorry,
Just a stupid error on my part ...
The token wasn't set!

**Comment by boncey** [comment]
Hooray! :-)
