### ISSUE TITLE
PhotosetsInterface.getList returns much smaller collection when not run in main thread

### ISSUE THREAD

**Issue by zeroxx1986** [callmeal/Flickr4Java#159]
Hello,

I've found a rather annoying bug(?) yesterday. I'm trying to create an uploader for myself with GUI (just for fun), and I would like the ability to select which album (photoset) I want to upload it to. Thing is, when the PhotosetsInterface.getList(userid) is called in my main thread (blocking the GUI while the request is ongoing), then the returned collection is fine, every photoset is in there, the collection's size is 517 (Yes, I have that many photosets). 
As the request takes a rather noticable time, I've tried it to move to a non-main thread via Runnable & Thread.run(); so it won't block the UI. This way, the code gets executed, no errors or warnings are present, but the returned collection only has 29 elements! No matter how many times I execute the script, every time it returns 29 elements if ran in a thread other than the main thread.
Do you have any suggestions where the problem can be? (Yes, I know the library is not thread-safe, but I'm not trying to access it between threads, or at least I think I'm not doing anything like this - no other logic is running in my code related to this library) 

If you need, I can provide a sample code; right now I only have my full application which uses Qt Jambi, etc. so it's rather cumbersome to use that.

Thanks in advance,
Z

**Comment by boncey** [comment]
Hmmm, is the thread timing out perhaps?

Are you using the `ScheduledExecutorService` by the way - it's a lot easier to work with than the raw thread API?

Otherwise, I'm not sure there's anything I can add.
I doubt it's related directly to F4J so I'm closing this for now.
Will re-open if you provide more information.
