### ISSUE TITLE
Dependent radiolist in Yii2

### ISSUE THREAD

**Issue by farisjemal** [callmeal/Flickr4Java#160]
I am working on a laboratory management system. I have tests and test items. I want to show the tests and test items to be listed as radio button. When I click on the test radio buttons, the radio buttons with value with test items inside the test I have chosen will be displayed. How can I make two separate radio lists to be dependent on each other? Thanks in advance.

**Comment by farisjemal** [comment]
![image1](https://cloud.githubusercontent.com/assets/15874095/11783216/d1154fca-a22a-11e5-8eea-2fca833d143e.png)

**Comment by farisjemal** [comment]
I want to change the check boxes into radio buttons here!

![image1](https://cloud.githubusercontent.com/assets/15874095/11783226/e2539f3a-a22a-11e5-954d-d40ff63568c6.png)

**Comment by boncey** [comment]
This has nothing to do with this project so I am closing it.
