### ISSUE TITLE
Invalid Operation Exception

### ISSUE THREAD

**Issue by Vishnuvardhana1989** [callmeal/Flickr4Java#166]
getting error in this line for SMS application

request.Content Length = bytearray.length 
 it saying  property cannot be set  after writing has started. Please suggest any solutions for this.

**Comment by boncey** [comment]
Can you give me some pointers as to where in the Flickr4Java code this is happening please?

**Comment by boncey** [comment]
I don't think this is an F4J issue so am closing it.
