### ISSUE TITLE
OAuth not calling Callback URL when user says "No Thanks"

### ISSUE THREAD

**Issue by Linus12** [callmeal/Flickr4Java#170]
### Issue Description
I recently modified a desktop app to use a Call Back Server during the OAuth process. This works much better because the user doesn't have to copy or paste anything from Flickr back to the app. Flickr displays the Authentication screen just fine and when the user presses the "OK, I Accept" button, the Call Back URL is processed, and I have the Tokens I need to finish the OAuth process.
Thumbs up, this works great!!!

The issue is when the user presses the "No Thanks" button on the Flickr Authorization screen. Other systems, like Tumblr, will still call the Call Back URL with no token strings. (Using the same version of org.scribe (1.3.5).

Flickr just goes to the home screen and never calls the Call Back URL. So my app is sitting there waiting for something that never calls them back!

Yes, I have a timeout on my App, but even with a short three minute time out I hate to have the App just sitting there when the Flickr Screen is displaying as if nothing is wrong.

Shouldn't the Flickr Authorization Screen call the Call Back URL in such a way that indicates the user has declined? or is there another URL to pass for "declines"?

### Your environment
*  Flickr4Java:  2.15
*  org.scribe: 1.3.5
*  org.apache.log4j: 1.2.17
*  JDK: 1.8.0_31

### Steps to reproduce
User your app and callback URL to authorize a Flickr App. Select "No Thanks". The callback URL doesn't seem to be called.

### Expected behavior
The App shows Flickr Authentication screen using the provided URL. The user presses the "No Thanks" button on the Flickr Authorization screen. The Call Back URL is called with no token strings.
or with the tokens set to a blank string.
 
### Actual behavior
The App calls shows Flickr Authentication screen using the provided URL. The user presses the "No Thanks" button on the Flickr Authorization screen. The user is show their Flickr Home Page.

### Log
```
N/A or I need instructions in producing one.

```
### Additional Comments
I have no problems testing this with my app and am looking for possible solutions/debugging tips. I understand how busy everyone is, but Flickr API "Support" seems to have NO interest in supporting their own API. I just don't know if this is a Flickr4Java issue, a Scribe (JSON) issue, or an issue with the Flickr authentication screen.

I do know that I am using the same process,same Scribe Version, same JDK version, the same callback server (different URL) for my authorization to Tumblr, and the "No Thanks" process works just fine. So I'm just a bit frustrated. Any help or direction to look would be most appreciated.

**Comment by boncey** [comment]
Hmmm, I just had a look at one of my websites that uses F4J and Scribe.
It works as follows.

If I click `No Thanks` it ends up on the "about page" of my application.
That initially made no sense to me but then when I looked at the app page within Flickr I saw that I had the URL to the about page as my app URL underneath the `Visit website` button on the right-hand side (you can change that URL by clicking it).

So, the URL underneath that button is the URL users will be taken to if they cancel.
Unfortunately that is also the URL displayed to everyone that looks at your app page.

I think that workflow is OK for a website but is a bit clunky if you are just waiting for callbacks.
Not sure what the best approach is for you I'm afraid.
I've not used a separate callback server so can't really help much I think.

Hopefully my investigation helps though.
I'll close this as I don't think it's an F4J problem but you're welcome to leave more comments and questions etc.
