### ISSUE TITLE
[Minecraft Forge] 

### ISSUE THREAD

**Issue by LyrasDerEchte** [callmeal/Flickr4Java#180]
Hello folks,

I do not get ahead because I hang on one thing in my project for a relatively long time.
I want to create an event which gets fired when I dismount from my horse.

My "HorseEvent"-Class:
`public class HorseEvent extends EntityEvent {

	/*
	 * EntityHorse being used for the event
	 * examples: mounting/dismounting , feeding , giving a saddle
	 */
	public final EntityHorse entity;
	
	/**
	 * Creates a new event for an EntityHorse.
	 * 
	 * @param entityHorse The EntityHorse for this event
	 */
	public HorseEvent ( EntityHorse entityHorse ) {
		
		super ( entityHorse );
		this.entity = entityHorse;
		
	}
	
}`

My "HorseDismountEvent"-Class:
`/**
 * Event that is fired whenever a player dismounts his horse.
 */
@Cancelable
public class HorseDismountEvent extends HorseEvent {

	/*
	 * The player dismounting the horse.
	 */
	public final EntityPlayer player;
	
	/**
	 * Creates a new event for EntityHorse dismounted by a player.
	 * 
	 * @param entityHorse The EntityHorse being dismounted.
	 * @param player The Player dismounting the horse.
	 */
	public HorseDismountEvent ( EntityHorse entityHorse , EntityPlayer player ) {
		
		super ( entityHorse );
		this.player = player;
		System.out.println( "Calling HorseDismountEvent" );
		
		ItemTossEvent event;
		
	}
	
}`

My concrete problem is that I don't know how to call the events and how to test if I dismount from the horse. I don't know either how to register this event.

For example:
The Forge-Class "ItemTossEvent":
`/**
 * Event that is fired whenever a player tosses (Q) an item or drag-n-drops a
 * stack of items outside the inventory GUI screens. Canceling the event will
 * stop the items from entering the world, but will not prevent them being
 * removed from the inventory - and thus removed from the system.
 */
@Cancelable
public class ItemTossEvent extends ItemEvent
{

    /**
     * The player tossing the item.
     */
    public final EntityPlayer player;

    /**
     * Creates a new event for EntityItems tossed by a player.
     * 
     * @param entityItem The EntityItem being tossed.
     * @param player The player tossing the item.
     */
    public ItemTossEvent(EntityItem entityItem, EntityPlayer player)
    {
        super(entityItem);
        this.player = player;
    }
}`

This class got no code which tests if the player tosses his item and I don't understand why this is working...

The Forge-Class "ItemEvent":
`/**
 * Base class for all EntityItem events. Contains a reference to the
 * EntityItem of interest. For most EntityItem events, there's little to no
 * additional useful data from the firing method that isn't already contained
 * within the EntityItem instance.
 */
public class ItemEvent extends EntityEvent
{
    /**
     * The relevant EntityItem for this event, already cast for you.
     */
    public final EntityItem entityItem;

    /**
     * Creates a new event for an EntityItem.
     * 
     * @param itemEntity The EntityItem for this event
     */
    public ItemEvent(EntityItem itemEntity)
    {
        super(itemEntity);
        this.entityItem = itemEntity;
    }
}`

Thanks in advance, Lyras ;)
PS: S0rry f0r my b4d 3nglish

**Comment by LyrasDerEchte** [comment]
Either I'm too stupid to use the functions or they are incorrect.

**Comment by boncey** [comment]
Please explain the relevance to this project.

**Comment by LyrasDerEchte** [comment]
Öhm...
I don't know what to say.

**Comment by LyrasDerEchte** [comment]
I just clicked the "New Issue"-Button because I need help xP

**Comment by boncey** [comment]
Sorry, wrong project so I can't help you.
